import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Plus } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/lib/external-supabase";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageHeader, Surface } from "@/components/app/page";
import { fmtMoney, friendlyError } from "@/lib/format";
import type { Database } from "@/integrations/supabase/types";
type Plan = Database["public"]["Tables"]["plans"]["Row"];
export const Route = createFileRoute("/_authenticated/plans")({ head: () => ({ meta: [{ title: "Plans — Lift & Fit" }, { name: "description", content: "Manage Lift & Fit membership plans." }, { property: "og:title", content: "Plans — Lift & Fit" }, { property: "og:description", content: "Manage Lift & Fit membership plans." }] }), component: Plans });
function Plans() { const [rows, setRows] = useState<Plan[]>([]); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [months, setMonths] = useState(""); async function load() { const { data } = await supabase.from("plans").select("*").order("created_at"); setRows(data ?? []); } useEffect(() => { void load(); }, []); async function add(): Promise<void> { if (!name.trim() || Number(amount) <= 0 || !Number.isInteger(Number(months)) || Number(months) <= 0) { toast.error("Enter a name, positive amount, and whole-number duration."); return; } const { error } = await supabase.from("plans").insert({ name: name.trim(), amount: Number(amount), duration_months: Number(months), is_active: true }); if (error) toast.error(friendlyError(error)); else { toast.success("Plan added."); setOpen(false); setName(""); setAmount(""); setMonths(""); await load(); } } return <><PageHeader title="Plans" description="Add plans for future memberships. Existing plans are retained for payment history." actions={<Button onClick={() => setOpen(true)}><Plus />Add Plan</Button>} /><Surface><Table><TableHeader><TableRow><TableHead>Plan Name</TableHead><TableHead>Amount</TableHead><TableHead>Duration</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map((p) => <TableRow key={p.id}><TableCell className="font-medium">{p.name}</TableCell><TableCell>{fmtMoney(p.amount)}</TableCell><TableCell>{p.duration_months} months</TableCell><TableCell><Badge variant={p.is_active ? "active" : "inactive"}>{p.is_active ? "Active" : "Inactive"}</Badge></TableCell></TableRow>)}</TableBody></Table></Surface><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Add Plan</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Plan Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="space-y-2"><Label>Amount (₹)</Label><Input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} /></div><div className="space-y-2"><Label>Duration (months)</Label><Input type="number" value={months} onChange={(e) => setMonths(e.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void add()}>Add Plan</Button></DialogFooter></DialogContent></Dialog></>; }